GET http://localhost:4000/user-api/users

### Read users by ObjectID
GET http://localhost:4000/user-api/users/697dba7d2d98bc550c07face

###Update user
PUT http://localhost:4000/user-api/users/697dba7d2d98bc550c07face
Content-Type: application/json

{
    "username":"Divya Boddam",
    "password":"DivyaBoddam",
    "age":20
}

###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"Divya Boddam",
    "password":"divyaboddam",
    "age":20
}

### delete user
DELETE http://localhost:4000/user-api/users/697dba7d2d98bc550c07face


### product project
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productid":102,
    "productName":"Keyboard",
    "price":4000
}

###
GET http://localhost:4000/product-api/products



###
GET http://localhost:4000/product-api/products/697dd06fd224b341bcff12e3


###
PUT http://localhost:4000/product-api/products/697dd06fd224b341bcff12e3
Content-Type: application/json

{
    "productid":101,
    "productName":"Monitor",
    "price":12999
}

###
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username":"Divya Boddam",
    "password":"divyaboddam"
}

###Req for protected route
GET http://localhost:4000/user-api/test


